[2022-11-05 14:52:01,630] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_tax_receipts.find_large_receipts 2022-11-04T14:51:29.395015+00:00 [queued]>
[2022-11-05 14:52:01,684] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_tax_receipts.find_large_receipts 2022-11-04T14:51:29.395015+00:00 [queued]>
[2022-11-05 14:52:01,686] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-11-05 14:52:01,687] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-11-05 14:52:01,688] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-11-05 14:52:01,724] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): find_large_receipts> on 2022-11-04T14:51:29.395015+00:00
[2022-11-05 14:52:01,743] {standard_task_runner.py:52} INFO - Started process 88 to run task
[2022-11-05 14:52:01,761] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_tax_receipts', 'find_large_receipts', '2022-11-04T14:51:29.395015+00:00', '--job-id', '37', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/texas_dags.py', '--cfg-path', '/tmp/tmpawub3rsy', '--error-file', '/tmp/tmpbl7kojf9']
[2022-11-05 14:52:01,763] {standard_task_runner.py:77} INFO - Job 37: Subtask find_large_receipts
[2022-11-05 14:52:01,902] {logging_mixin.py:104} INFO - Running <TaskInstance: get_tax_receipts.find_large_receipts 2022-11-04T14:51:29.395015+00:00 [running]> on host c0f23e4d7a13
[2022-11-05 14:52:02,077] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_tax_receipts
AIRFLOW_CTX_TASK_ID=find_large_receipts
AIRFLOW_CTX_EXECUTION_DATE=2022-11-04T14:51:29.395015+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-04T14:51:29.395015+00:00
[2022-11-05 14:52:02,085] {logging_mixin.py:104} INFO - found large receipts
[2022-11-05 14:52:02,088] {python.py:118} INFO - Done. Returned value was: None
[2022-11-05 14:52:02,126] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=get_tax_receipts, task_id=find_large_receipts, execution_date=20221104T145129, start_date=20221105T145201, end_date=20221105T145202
[2022-11-05 14:52:02,201] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-05 14:52:02,229] {local_task_job.py:146} INFO - Task exited with return code 0
